dbt unit test for views in DM
crassula-ovata/data_and_analytics_dbt_bha pull request #43
Opened 2024-06-20 18:14 UTC by shuclu

2024-06-20 18:18 UTC, shuclu commented
@binrai hey can you take a look at this PR for all the dbt unit test changes?

2024-06-21 15:43 UTC, binrai requested changes
Have some open questions for you.

2024-06-21 15:43 UTC, binrai commented on tests/generic/unique_combination_of_columns.sql
Looks like this is not used - is it meant to not be used at the moment?

2024-06-21 17:31 UTC, shuclu commented on models/DM_DB/DM/Views/dm_views_config.yml
data_tests is required for dbt v1.8, you can change your dbt docs version to v1.8 to see the reference. 

generic tests should only be triggered when called in the config yml file. when you said they don't popup even when it's called?

also, you might need to upgrade your dbt to v1.8. i did it because the latest version was used in github action.
i updated the confluence doc, there is a dbt upgrade command there. 
https://dimagi.atlassian.net/wiki/spaces/USH/pages/2274689025/D+A+Snowflake+Version+Control+and+CI+CD+in+DBT+and+Github

2024-06-21 17:31 UTC, shuclu commented on tests/check_vw_tableau_clinic_filter.sql
let me check on this..

2024-06-21 20:20 UTC, binrai commented on models/DM_DB/DM/Views/dm_views_config.yml
Got it.

2024-06-21 21:01 UTC, binrai approved these changes

2024-06-21 21:02 UTC, shuclu commented on tests/generic/unique_combination_of_columns.sql
yes that correct, did it and realize that i don't need it for now. but it can be used in the future

2024-06-21 21:30 UTC, merged